# Welcome to NumPy Tutorial 

In [1]:
import numpy as np

In [2]:
myArr = np.array([3, 10, 5500000, 15])

In [3]:
myArr

array([ 3, 10, 55, 15])

In [4]:
myArr = np.array([3, 10, 5500000, 15], np.int8) #should not be large number

In [5]:
myArr #will give error to print the large number

array([ 3, 10, 96, 15], dtype=int8)

In [6]:
myArr = np.array([3, 10, 5500000, 15], np.int64) #can hold large number

In [7]:
myArr

array([      3,      10, 5500000,      15], dtype=int64)