# Welcome to NumPy Tutorial 

In [1]:
import numpy as np

In [2]:
myArr = np.array([3, 10, 5500000, 15])

In [3]:
myArr

array([      3,      10, 5500000,      15])

In [4]:
myArr = np.array([3, 10, 5500000, 15], np.int8) #should not be large number

In [5]:
myArr #will give error to print the large number

array([ 3, 10, 96, 15], dtype=int8)

In [6]:
myArr = np.array([3, 10, 5500000, 15], np.int64) #can hold large number

In [7]:
myArr

array([      3,      10, 5500000,      15], dtype=int64)

In [8]:
# myArr[0,1] 
# gives error as the original array is 1D array, where we wanted to find an element for 2D array

In [9]:
myArr[2]

5500000

In [10]:
arr = np.array([[20, 50, 1, 66]], np.int32) #2D array

In [11]:
arr[0,2] #getting an element from 2D array

1

In [12]:
arr[0,2] = 100 #changing the value of the element with 0th row and 3rd column

In [13]:
arr

array([[ 20,  50, 100,  66]])

In [14]:
arr.shape #row vs column details

(1, 4)

In [15]:
arr.dtype

dtype('int32')

In [16]:
"""
There are 6 general mechanisms for creating arrays:

- Conversion from other Python structures (i.e. lists and tuples)

- Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

- Replicating, joining, or mutating existing arrays

- Reading arrays from disk, either from standard or custom formats

- Creating arrays from raw bytes through the use of strings or buffers

- Use of special library functions (e.g., random)
"""

'\nThere are 6 general mechanisms for creating arrays:\n\n- Conversion from other Python structures (i.e. lists and tuples)\n\n- Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)\n\n- Replicating, joining, or mutating existing arrays\n\n- Reading arrays from disk, either from standard or custom formats\n\n- Creating arrays from raw bytes through the use of strings or buffers\n\n- Use of special library functions (e.g., random)\n'

### Array creation: Conversion from other Python structures (i.e. lists and tuples)

In [17]:
listArray = np.array([[1, 2, 3], [55, 25, 85], [6, 58, 4]])

In [18]:
listArray

array([[ 1,  2,  3],
       [55, 25, 85],
       [ 6, 58,  4]])

In [19]:
listArray.dtype

dtype('int32')

In [20]:
listArray.shape

(3, 3)

In [21]:
listArray.size

9

In [22]:
np.array({25, 20, 88}) #converting data type to object

array({88, 25, 20}, dtype=object)