# Learning NumPy Module

In [1]:
import numpy as np

In [2]:
myArr = np.array([3, 10, 5500000, 15])

In [3]:
myArr

array([      3,      10, 5500000,      15])

In [4]:
myArr = np.array([3, 10, 5500000, 15], np.int8) #should not be large number

In [5]:
myArr #will give error to print the large number

array([ 3, 10, 96, 15], dtype=int8)

In [6]:
myArr = np.array([3, 10, 5500000, 15], np.int64) #can hold large number

In [7]:
myArr

array([      3,      10, 5500000,      15], dtype=int64)

In [8]:
# myArr[0,1] 
# gives error as the original array is 1D array, where we wanted to find an element for 2D array

In [9]:
myArr[2]

5500000

In [10]:
arr = np.array([[20, 50, 1, 66]], np.int32) #2D array

In [11]:
arr[0,2] #getting an element from 2D array

1

In [12]:
arr[0,2] = 100 #changing the value of the element with 0th row and 3rd column

In [13]:
arr

array([[ 20,  50, 100,  66]])

In [14]:
arr.shape #row vs column details

(1, 4)

In [15]:
arr.dtype

dtype('int32')

In [16]:
"""
There are 6 general mechanisms for creating arrays:

- Conversion from other Python structures (i.e. lists and tuples)

- Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

- Replicating, joining, or mutating existing arrays

- Reading arrays from disk, either from standard or custom formats

- Creating arrays from raw bytes through the use of strings or buffers

- Use of special library functions (e.g., random)
"""

'\nThere are 6 general mechanisms for creating arrays:\n\n- Conversion from other Python structures (i.e. lists and tuples)\n\n- Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)\n\n- Replicating, joining, or mutating existing arrays\n\n- Reading arrays from disk, either from standard or custom formats\n\n- Creating arrays from raw bytes through the use of strings or buffers\n\n- Use of special library functions (e.g., random)\n'

### Array: Creation, Different Attributes & Functions

In [17]:
listArray = np.array([[1, 2, 3], [55, 25, 85], [6, 58, 4]])

In [18]:
listArray

array([[ 1,  2,  3],
       [55, 25, 85],
       [ 6, 58,  4]])

In [19]:
listArray.dtype

dtype('int32')

In [20]:
listArray.shape

(3, 3)

In [21]:
listArray.size

9

In [22]:
np.array({25, 20, 88}) #converting data type to object

array({88, 25, 20}, dtype=object)

In [23]:
zeros = np.zeros ((2, 5))

In [24]:
zeros  # creates an array of (2,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
zeros.dtype

dtype('float64')

In [26]:
zeros.shape

(2, 5)

In [27]:
rng = np.arange(12)  # creates a NumPy array in the range of 0 to (n-1)

In [28]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
lspace = np.linspace (1, 50, 10)  # give 10 numbers between range 1 to 50 having equal diff between any two

In [30]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [31]:
emp = np.empty((4 , 6))  # assigns an (4, 6) array with random elements

In [32]:
emp

array([[1.34424122e-306, 6.99405043e-009, 2.93494529e+222,
        1.03063392e-113, 1.72731111e+097, 6.99416121e-009],
       [2.93494530e+222, 1.03063392e-113, 1.05894612e-153,
        7.61402229e-010, 8.98752578e-153, 4.83245960e+276],
       [8.03704345e-095, 1.95575364e-109, 1.05190656e-153,
        4.41430940e-308, 8.30632685e-307, 1.03063392e-113],
       [1.05177053e-153, 7.04134408e-009, 1.43178810e-065,
        1.35717430e+131, 1.05176086e-153, 5.03392224e+180]])

In [33]:
emp_like = np.empty_like(lspace)  # return a new array with the same shape and type as a given array which can be initialized later

In [34]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [35]:
identity = np.identity(45)  # creates (45,45) array of identity element

In [36]:
identity

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [37]:
arr = np.arange (99)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
arr = arr.reshape (3, 33)  # reshapes the (1, 99) array to (3, 33)

In [40]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [41]:
arr = arr.ravel()  # gives 1D array

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
x = [[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [44]:
ar = np.array(x)

In [45]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [46]:
ar.sum(axis=0)  # axis=0 means row direction in 2D shape (axis=1 means column direction) & for 1D array it is axis=0

array([12,  8,  9])

In [47]:
ar.T  # transpose of the array

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [48]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [49]:
ar.flat  # iteration through the array

In [50]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [51]:
ar.ndim  # number of dimension

2

In [52]:
ar.size  # number of elements

9

In [53]:
ar.nbytes  # total bytes consumed by the array

36

In [54]:
one = np.array([1, 3, 5, 665, 85])

In [55]:
one.argmax()  # index of max element

3

In [56]:
one.argmin()  # index of min element

0

In [57]:
one.argsort()  # index to sort the array

array([0, 1, 2, 4, 3], dtype=int32)

In [58]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [59]:
ar.argmin()  # index for min element in 2D array

8

In [60]:
ar.argmax()  # index for max element in 2D array

6

In [61]:
ar.argmax(axis=0)  # index for max element in 2D array but in row direction

array([2, 1, 1], dtype=int32)

In [62]:
ar.argmax(axis=1)  # index for max element in 2D array but in column direction

array([2, 2, 0], dtype=int32)

In [63]:
ar.argsort(axis=1)  # sorting through column index

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int32)

In [64]:
ar.argsort(axis=0)  # sorting through row index

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int32)

### Mathematical Operations

In [65]:
ar1 = np.array([[1, 2, 5], [2, 5, 8], [0, 1, 2]])

In [66]:
ar2 = np.array([[3, -1, -2], [-2, 3, 1], [2, 0, -4]])

In [67]:
ar1

array([[1, 2, 5],
       [2, 5, 8],
       [0, 1, 2]])

In [68]:
ar2

array([[ 3, -1, -2],
       [-2,  3,  1],
       [ 2,  0, -4]])

In [69]:
ar1 + ar2  # gives summation

array([[ 4,  1,  3],
       [ 0,  8,  9],
       [ 2,  1, -2]])

In [70]:
ar1 * ar2  # does multiplication

array([[  3,  -2, -10],
       [ -4,  15,   8],
       [  0,   0,  -8]])

In [71]:
np.sqrt(ar1)  # gives sq. root for each eliment of ar1 array (gives error if any element is negative)

array([[1.        , 1.41421356, 2.23606798],
       [1.41421356, 2.23606798, 2.82842712],
       [0.        , 1.        , 1.41421356]])

In [72]:
ar1.sum()  # summation of all elements in ar1 array

26

In [73]:
ar1.max()  # highest element in ar1

8

In [74]:
ar1.min()  # lowest element in ar1

0

In [75]:
ar1

array([[1, 2, 5],
       [2, 5, 8],
       [0, 1, 2]])

In [76]:
np.where(ar1>3)  # tells position of element greater than 2 (row from first tuple, column from second tuple)

(array([0, 1, 1], dtype=int32), array([2, 1, 2], dtype=int32))

In [77]:
type(np.where(ar1>3))

tuple

In [78]:
np.count_nonzero(ar1)  # total number of nonzero elements

8

In [79]:
np.nonzero(ar1)  # positions of nonzero elements

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int32),
 array([0, 1, 2, 0, 1, 2, 1, 2], dtype=int32))

In [80]:
import sys

In [81]:
py_ar = [0, 4, 55, 2]

In [82]:
np_ar = np.array(py_ar)

In [83]:
sys.getsizeof(1) * len(py_ar)  # size of python array

56

In [84]:
np_ar.itemsize * np_ar.size  # size of NumPy array

16

In [86]:
np_ar.tolist()  # NumPy array to python array

[0, 4, 55, 2]