# Learning NumPy Module

In [1]:
import numpy as np

In [2]:
myArr = np.array([3, 10, 5500000, 15])

In [3]:
myArr

array([      3,      10, 5500000,      15])

In [4]:
myArr = np.array([3, 10, 5500000, 15], np.int8) #should not be large number

In [5]:
myArr #will give error to print the large number

array([ 3, 10, 96, 15], dtype=int8)

In [6]:
myArr = np.array([3, 10, 5500000, 15], np.int64) #can hold large number

In [7]:
myArr

array([      3,      10, 5500000,      15], dtype=int64)

In [8]:
# myArr[0,1] 
# gives error as the original array is 1D array, where we wanted to find an element for 2D array

In [9]:
myArr[2]

5500000

In [10]:
arr = np.array([[20, 50, 1, 66]], np.int32) #2D array

In [11]:
arr[0,2] #getting an element from 2D array

1

In [12]:
arr[0,2] = 100 #changing the value of the element with 0th row and 3rd column

In [13]:
arr

array([[ 20,  50, 100,  66]])

In [14]:
arr.shape #row vs column details

(1, 4)

In [15]:
arr.dtype

dtype('int32')

In [16]:
"""
There are 6 general mechanisms for creating arrays:

- Conversion from other Python structures (i.e. lists and tuples)

- Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

- Replicating, joining, or mutating existing arrays

- Reading arrays from disk, either from standard or custom formats

- Creating arrays from raw bytes through the use of strings or buffers

- Use of special library functions (e.g., random)
"""

'\nThere are 6 general mechanisms for creating arrays:\n\n- Conversion from other Python structures (i.e. lists and tuples)\n\n- Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)\n\n- Replicating, joining, or mutating existing arrays\n\n- Reading arrays from disk, either from standard or custom formats\n\n- Creating arrays from raw bytes through the use of strings or buffers\n\n- Use of special library functions (e.g., random)\n'

### Array: Creation, Different Attributes & Functions

In [17]:
listArray = np.array([[1, 2, 3], [55, 25, 85], [6, 58, 4]])

In [18]:
listArray

array([[ 1,  2,  3],
       [55, 25, 85],
       [ 6, 58,  4]])

In [19]:
# Get a specific row 
listArray[0, :]

array([1, 2, 3])

In [20]:
listArray.dtype

dtype('int32')

In [21]:
listArray.shape

(3, 3)

In [22]:
listArray.size

9

In [23]:
np.array({25, 20, 88}) #converting data type to object

array({88, 25, 20}, dtype=object)

In [24]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [25]:
# Getting elements in a specific range [axis, startindex:endindex:stepsize]
a[1, 2:5:2]

array([10, 12])

In [26]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
# Get specific element (work outside in)
b[0,1,1]

4

In [28]:
rng = np.arange(12)  # creates a NumPy array in the range of 0 to (n-1)

In [29]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
lspace = np.linspace (1, 50, 10)  # give 10 numbers between range 1 to 50 having equal diff between any two

In [31]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [32]:
emp = np.empty((4 , 6))  # assigns an (4, 6) array with random elements

In [33]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.11261434e-306, 4.45055939e-308, 6.23061763e-307],
       [6.23053954e-307, 9.34609790e-307, 8.45593934e-307,
        9.34600963e-307, 1.86921143e-306, 6.23061763e-307],
       [8.90104239e-307, 8.01089062e-307, 1.02359848e-306,
        1.60219035e-306, 1.60220393e-306, 1.05700515e-307],
       [1.11261774e-306, 8.34423917e-308, 8.34445138e-308,
        7.56577398e-307, 9.34600284e-307, 3.75603081e-317]])

In [34]:
emp_like = np.empty_like(lspace)  # return a new array with the same shape and type as a given array which can be initialized later

In [35]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [36]:
arr = np.arange (99)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
arr = arr.reshape (3, 33)  # reshapes the (1, 99) array to (3, 33)

In [39]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [40]:
arr = arr.ravel()  # gives 1D array

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
x = [[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [43]:
ar = np.array(x)

In [44]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [45]:
ar.sum(axis=0)  # axis=0 means row direction in 2D shape (axis=1 means column direction) & for 1D array it is axis=0

array([12,  8,  9])

In [46]:
ar.T  # transpose of the array

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [48]:
ar.flat  # iteration through the array

In [49]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [50]:
ar.ndim  # number of dimension

2

In [51]:
ar.size  # number of elements

9

In [52]:
ar.nbytes  # total bytes consumed by the array

36

In [53]:
one = np.array([1, 3, 5, 665, 85])

In [54]:
one.argmax()  # index of max element

3

In [55]:
one.argmin()  # index of min element

0

In [56]:
one.argsort()  # index to sort the array

array([0, 1, 2, 4, 3], dtype=int32)

In [57]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [58]:
ar.argmin()  # index for min element in 2D array

8

In [59]:
ar.argmax()  # index for max element in 2D array

6

In [60]:
ar.argmax(axis=0)  # index for max element in 2D array but in row direction

array([2, 1, 1], dtype=int32)

In [61]:
ar.argmax(axis=1)  # index for max element in 2D array but in column direction

array([2, 2, 0], dtype=int32)

In [62]:
ar.argsort(axis=1)  # sorting through column index

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int32)

In [63]:
ar.argsort(axis=0)  # sorting through row index

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int32)

### Initializing Different Types of Arrays

In [64]:
zeros = np.zeros ((2, 5))  # creates an array of (2,5) with all zero

In [65]:
zeros 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
zeros.dtype

dtype('float64')

In [67]:
zeros.shape

(2, 5)

In [68]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [69]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [70]:
# Any other number (full_like) to any previous array shape
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [71]:
# Array with random decimal numbers
np.random.rand(4,2)

array([[0.15651321, 0.42691604],
       [0.24292846, 0.81099553],
       [0.18872842, 0.64614264],
       [0.25798021, 0.32770052]])

In [72]:
# Array with random decimal numbers with the same shape of another array
np.random.random_sample(a.shape)

array([[0.67948734, 0.84566826, 0.93829307, 0.48109166, 0.19099067,
        0.59169459, 0.05090006],
       [0.74854857, 0.55765109, 0.7265664 , 0.26231284, 0.8029998 ,
        0.5664156 , 0.0897564 ]])

In [73]:
# Array with random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-4, -1,  6],
       [-4,  3, -3],
       [ 5,  0, -3]])

In [74]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [75]:
# Repeating an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [76]:
# building required array

output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z  # or we can use:  output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [77]:
a = np.array([1,2,3]) 
b = a.copy()  # if we don't use copy then changing the value of b will also change the value of a
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


### Mathematical Operations

In [78]:
ar1 = np.array([[1, 2, 5], [2, 5, 8], [0, 1, 2]])

In [79]:
ar2 = np.array([[3, -1, -2], [-2, 3, 1], [2, 0, -4]])

In [80]:
ar1

array([[1, 2, 5],
       [2, 5, 8],
       [0, 1, 2]])

In [81]:
ar2

array([[ 3, -1, -2],
       [-2,  3,  1],
       [ 2,  0, -4]])

In [82]:
ar1 + ar2  # gives summation

array([[ 4,  1,  3],
       [ 0,  8,  9],
       [ 2,  1, -2]])

In [83]:
ar1 * ar2  # does multiplication

array([[  3,  -2, -10],
       [ -4,  15,   8],
       [  0,   0,  -8]])

In [84]:
np.sqrt(ar1)  # gives sq. root for each eliment of ar1 array (gives error if any element is negative)

array([[1.        , 1.41421356, 2.23606798],
       [1.41421356, 2.23606798, 2.82842712],
       [0.        , 1.        , 1.41421356]])

In [85]:
ar1.sum()  # summation of all elements in ar1 array

26

In [86]:
ar1.max()  # highest element in ar1

8

In [87]:
ar1.min()  # lowest element in ar1

0

In [88]:
ar1

array([[1, 2, 5],
       [2, 5, 8],
       [0, 1, 2]])

In [89]:
np.where(ar1>3)  # tells position of element greater than 2 (row from first tuple, column from second tuple)

(array([0, 1, 1], dtype=int32), array([2, 1, 2], dtype=int32))

In [90]:
type(np.where(ar1>3))

tuple

In [91]:
np.count_nonzero(ar1)  # total number of nonzero elements

8

In [92]:
np.nonzero(ar1)  # positions of nonzero elements

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int32),
 array([0, 1, 2, 0, 1, 2, 1, 2], dtype=int32))

In [93]:
import sys

In [94]:
py_ar = [0, 4, 55, 2]

In [95]:
np_ar = np.array(py_ar)

In [96]:
sys.getsizeof(1) * len(py_ar)  # size of python array

56

In [97]:
np_ar.itemsize * np_ar.size  # size of NumPy array

16

In [98]:
np_ar.tolist()  # NumPy array to python array

[0, 4, 55, 2]

In [99]:
ar1 ** 2  # gives sqaure for each elements

array([[ 1,  4, 25],
       [ 4, 25, 64],
       [ 0,  1,  4]], dtype=int32)

In [100]:
# take the sin of each elements
np.sin(ar1)

array([[ 0.84147098,  0.90929743, -0.95892427],
       [ 0.90929743, -0.95892427,  0.98935825],
       [ 0.        ,  0.84147098,  0.90929743]])

### Linear Algebra

In [101]:
a = np.ones((2,3) )
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)   # matrix multiplication function

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [102]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [103]:
# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### Statistics

In [104]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
np.min(stats)  # min of the array

1

In [106]:
np.max(stats)  

6

In [107]:
np.sum(stats, axis=0)   # sum of elements w.r.t. column

array([5, 7, 9])

### Reorganizing Arrays

In [108]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [109]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [110]:
# Vertically stacking vectors continues stacking
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [111]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

###### Load data from file

In [112]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')   # to make it as integer type
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


###### Boolean Masking and Advanced indexing

In [113]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [114]:
filedata[filedata > 50]   # grabing all the elements which have higher value of 50

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [115]:
# We can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [116]:
np.any(filedata > 50, axis=0)  # to check if any element has greater value than 50 in axis=0

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [117]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [118]:
(~((filedata > 50) & (filedata < 100)))  # reverse the previous query

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])